# Generated by Django 3.0.3 on 2020-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=80)),
                ('Topic_Name', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=250)),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
    ]
